version: '3.8'
services:
  fe-app:
    image: crpi-5yp7tlnljsjufyzm.cn-hangzhou.personal.cr.aliyuncs.com/cnblur/blue:a
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
         - /Users/cn/myssql-nest:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/cn/redis-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
