version: '3.8'
services:
  fe--admin-app:
    image: crpi-5yp7tlnljsjufyzm.cn-hangzhou.personal.cr.aliyuncs.com/cnblur/admin:a
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  fe-user-app:
    image: crpi-5yp7tlnljsjufyzm.cn-hangzhou.personal.cr.aliyuncs.com/cnblur/user:c
    ports:
      - 81:81
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    # ports:
    #   - 3005:3005
    depends_on:
      - mysql-container
      - redis-container
    restart: always
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
         - /Users/cn/myssql-nest:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置默认字符集
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - common-network
  redis-container:
    image: redis  
    volumes:
      - /Users/cn/redis-data:/data
    restart: always
    networks:
      - common-network
  minio-container:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /Users/cn/minio:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: root123
      MINIO_ROOT_PASSWORD: 123456789
    restart: always
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
